services:
  tesis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesis_gestos
    working_dir: /workspace
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    command: ["bash", "-lc", "sleep infinity"]
